### PR TITLE
fix(bootstrap): propagate interrupted flag through filter.rs

### LINKED ISSUE #83: bootstrap: propagate interrupted flag through filter.rs
From PR #69 super-review (Codex, MEDIUM):

`detect_interrupted()` in outcome.rs:202 uses `is_error` on the last tool call as a proxy for session interruption. The underlying `ToolCallRecord` doesn't carry the raw `interrupted` flag from the session log's `ToolUseResult`. This can cause false positives (a failing tool call != an interrupted session).

**Proposed fix:** Propagate `ToolUseResult::interrupted` through `filter.rs` into `ToolCallRecord`, and use it directly in `detect_interrupted()`.

Ref: PR #69 review thread PRRT_kwDORhq8Ws51cIym

### PR DESCRIPTION
**Pull request by dutiona**
## Summary

- Added `interrupted: bool` field to `ToolCallRecord`, populated from `ToolUseResult::interrupted` during enrichment in `extract_tool_calls()`
- Updated `detect_interrupted()` to use the real `interrupted` flag instead of `is_error` proxy, eliminating false positives
- Relaxed `Failure` classification: error loops, interruption, and negative sentiment are now independent failure signals
- Updated doc comments on `OutcomeSignals::was_interrupted` and `classify_outcome`

## Test plan

- [x] `reconstruct_propagates_interrupted_flag`
- [x] `reconstruct_interrupted_false_by_default`
- [x] `interrupted_flag_true_triggers_was_interrupted`
- [x] `is_error_alone_does_not_trigger_was_interrupted`
- [x] `error_loop_without_interruption_is_failure`
- [x] `classify_failure_error_loop_with_interruption`
- [x] `bootstrap_failure_session` integration test
- [x] All 46 bootstrap unit tests pass
- [x] All 8 bootstrap integration tests pass

## Review

- Gemini Code Assist: split combined test into two (addressed)
- Gemini CLI: MEDIUM on behavioral shift (intentional)
- Codex CLI: HIGH on classification regression (fixed in b00270f)

Fixes #83

### CODE REVIEW

File: src/bootstrap/outcome.rs [hunk 1]
```diff
@@ -53,7 +51,7 @@ pub enum Sentiment {
 /// | `has_commit` | `"git commit"` in tool input **or** commit-like patterns (`[main`, `[master`, 7+ hex chars) in stdout |
 /// | `tests_passed` | `"test result: ok"` / `"passed"` with test-runner patterns in stdout |
 /// | `has_error_loops` | Same stderr prefix (first 100 chars) in 3+ consecutive tool calls |
-/// | `was_interrupted` | Last `ToolCallRecord` has `is_error == true` (proxy — see [`OutcomeSignals::was_interrupted`]) |
+/// | `was_interrupted` | Last `ToolCallRecord` has `interrupted == true` (from `ToolUseResult::interrupted`) |
```
Comment (dutiona) [inline src/bootstrap/outcome.rs:54]: [Gemini Review] This change correctly addresses the limitation mentioned in the previous version, making `was_interrupted` a more precise indicator of session abandonment.

File: src/bootstrap/outcome.rs [hunk 2]
```diff
@@ -198,14 +196,14 @@ fn detect_error_loops(turns: &[super::filter::ConversationTurn]) -> bool {
...
-/// Proxy for interruption: the very last tool call's `is_error` flag.
+/// True when the very last tool call was interrupted.
 fn detect_interrupted(turns: &[super::filter::ConversationTurn]) -> bool {
     turns
         .iter()
         .rev()
         .flat_map(|t| t.tool_calls.iter().rev())
         .next()
-        .is_some_and(|tc| tc.is_error)
+        .is_some_and(|tc| tc.interrupted)
```
Comment (dutiona) [inline src/bootstrap/outcome.rs:207]: [Gemini Review] Swapping `is_error` for `interrupted` here is correct for detecting true interruptions. As a result, error loops that do not end with an explicit interruption will now be classified as `Indeterminate` instead of `Failure`. This is a better reflection of what the data actually shows.

File: src/bootstrap/filter.rs [hunk 3]
```diff
@@ -32,6 +32,7 @@ pub struct ToolCallRecord {
     pub stdout: Option<String>,
     pub stderr: Option<String>,
     pub is_error: bool,
+    pub interrupted: bool,
```
Comment (dutiona) [inline src/bootstrap/filter.rs:35]: [Gemini Review] Adding this field allows propagating the raw interruption status from the session log, which is more reliable than inferring it from error states.

**Review by dutiona — COMMENTED** [review]
[Gemini Review] This PR correctly implements the propagation of the interrupted flag from session logs. It improves the accuracy of the `was_interrupted` signal, which was previously proxied by a simple error check. The classification heuristics in `outcome.rs` have been updated and tested to reflect this more precise signal. Overall, it provides a much more robust detection of session abandonment.

File: src/bootstrap/outcome.rs [hunk 4]
```diff
@@ -417,6 +442,20 @@ mod tests {
...
+        tc.interrupted = true;
+        let turns = vec![make_turn("do thing", "ok", vec![tc])];
+        let (_, signals) = classify_outcome(&turns);
+        assert!(signals.was_interrupted);
+        // is_error alone no longer triggers was_interrupted
+        let tc_err = make_tool_call(None, Some("fail"), true);
+        let turns2 = vec![make_turn("do thing", "ok", vec![tc_err])];
+        let (_, signals2) = classify_outcome(&turns2);
+        assert!(!signals2.was_interrupted);
+    }
```
[the remark this answers is not in the document]
Comment (dutiona) [reply src/bootstrap/outcome.rs:461]: Fixed: split into two separate test functions as suggested — `interrupted_flag_true_triggers_was_interrupted` and `is_error_alone_does_not_trigger_was_interrupted`.

**Comment by dutiona** [comment]
**[Codex Review — Round 2]** (via CLI, shared file)

> **[HIGH]** `src/bootstrap/outcome.rs:81` — Requiring `was_interrupted` for `has_error_loops` to classify as `Failure` changes session semantics, not just interruption detection. Sessions with repeated tool errors but without `interrupted: true` would be mislabeled as `Indeterminate`.

**Resolution:** Fixed in commit `b00270f`. Changed Failure classification from `has_error_loops && was_interrupted` to `has_error_loops || was_interrupted || (negative_sentiment && !has_commit)`. Error loops, interruption, and negative sentiment are now independent failure signals. All 46 unit tests + 8 integration tests pass.
